FROM ubuntu:14.04

ARG ID
ENV BUILD_ID=$ID

# Install build-essential, git, wget and other dependencies
RUN apt-get update && apt-get install -y \
  build-essential \
  git \
  libopenblas-dev \
  python-dev \
  python-setuptools \
  wget \
  curl \
  nginx \
  supervisor \
  python-pip

ADD ./app /app
ADD ./config /config

RUN pip install -r /config/requirements.txt

#RUN pip install --upgrade boto3

EXPOSE 80

CMD ["python", "app/app.py"]