predictTaskDefinition:
    Properties:
      ContainerDefinitions:
      - Command:
        - DATE=`date -Iseconds` && echo "running predict_imagenet.py $IMAGEURL" && /usr/local/bin/predict_imagenet.py
          $IMAGEURL | tee results && echo "results being written to s3://$OUTPUTBUCKET/predict_imagenet.results.$HOSTNAME.$DATE.txt"
          && aws s3 cp results s3://$OUTPUTBUCKET/predict_imagenet.results.$HOSTNAME.$DATE.txt
          && echo "Task complete!"
        EntryPoint:
        - /bin/bash
        - -c
        Environment:
        - Name: IMAGEURL
          Value: https://images-na.ssl-images-amazon.com/images/G/01/img15/pet-products/small-tiles/23695_pets_vertical_store_dogs_small_tile_8._CB312176604_.jpg
        - Name: OUTPUTBUCKET
          Value:
            Ref: outputBucket
        - Name: AWS_DEFAULT_REGION
          Value:
            Ref: AWS::Region
        Image:
          Fn::Join:
          - ''
          - - Ref: AWS::AccountId
            - .dkr.ecr.
            - Ref: AWS::Region
            - .amazonaws.com/
            - Ref: ecrRepository
            - :latest
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: cloudWatchLogsGroup
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: predict_imagenet
        Memory: '2048'
        Name: ecs-deep-learning-workshop
        Privileged: 'true'
    Type: AWS::ECS::TaskDefinition